# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recoveryPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecoveryPasswordDialog(object):
    def setupUi(self, RecoveryPasswordDialog):
        RecoveryPasswordDialog.setObjectName("RecoveryPasswordDialog")
        RecoveryPasswordDialog.resize(1175, 797)
        self.widget = QtWidgets.QWidget(RecoveryPasswordDialog)
        self.widget.setGeometry(QtCore.QRect(-20, 0, 1221, 801))
        self.widget.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.widget.setObjectName("widget")
        self.recoveryPasswordLabel = QtWidgets.QLabel(self.widget)
        self.recoveryPasswordLabel.setGeometry(QtCore.QRect(380, 170, 471, 131))
        self.recoveryPasswordLabel.setStyleSheet("font: 21pt \"DejaVu Math TeX Gyre\";\n"
"color: black;")
        self.recoveryPasswordLabel.setObjectName("recoveryPasswordLabel")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 460, 451, 71))
        self.errorLabel.setStyleSheet("color: red;\n"
"font: 18pt \"Cantarell\";\n"
"")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.recoveryPasswordPushButton = QtWidgets.QPushButton(self.widget)
        self.recoveryPasswordPushButton.setGeometry(QtCore.QRect(380, 500, 261, 51))
        self.recoveryPasswordPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: green;")
        self.recoveryPasswordPushButton.setObjectName("recoveryPasswordPushButton")
        self.recoveryPasswordField = QtWidgets.QLineEdit(self.widget)
        self.recoveryPasswordField.setGeometry(QtCore.QRect(380, 310, 461, 71))
        self.recoveryPasswordField.setObjectName("recoveryPasswordField")
        self.cancelPushButton = QtWidgets.QPushButton(self.widget)
        self.cancelPushButton.setGeometry(QtCore.QRect(670, 500, 171, 51))
        self.cancelPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: red;")
        self.cancelPushButton.setObjectName("cancelPushButton")

        self.retranslateUi(RecoveryPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(RecoveryPasswordDialog)

    def retranslateUi(self, RecoveryPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        RecoveryPasswordDialog.setWindowTitle(_translate("RecoveryPasswordDialog", "Dialog"))
        self.recoveryPasswordLabel.setText(_translate("RecoveryPasswordDialog", "Восстановление пароля"))
        self.recoveryPasswordPushButton.setText(_translate("RecoveryPasswordDialog", "Сменить пароль"))
        self.recoveryPasswordField.setPlaceholderText(_translate("RecoveryPasswordDialog", "   Адрес электронной почты"))
        self.cancelPushButton.setText(_translate("RecoveryPasswordDialog", "Отмена"))
