# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renewPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenewPasswordDialog(object):
    def setupUi(self, RenewPasswordDialog):
        RenewPasswordDialog.setObjectName("RenewPasswordDialog")
        RenewPasswordDialog.resize(1175, 801)
        self.widget = QtWidgets.QWidget(RenewPasswordDialog)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 1221, 801))
        self.widget.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.widget.setObjectName("widget")
        self.recoveryPasswordLabel = QtWidgets.QLabel(self.widget)
        self.recoveryPasswordLabel.setGeometry(QtCore.QRect(380, 30, 471, 131))
        self.recoveryPasswordLabel.setStyleSheet("font: 21pt \"DejaVu Math TeX Gyre\";\n"
"color: black;")
        self.recoveryPasswordLabel.setObjectName("recoveryPasswordLabel")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 460, 451, 71))
        self.errorLabel.setStyleSheet("color: red;\n"
"font: 18pt \"Cantarell\";\n"
"")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.recoveryPasswordPushButton = QtWidgets.QPushButton(self.widget)
        self.recoveryPasswordPushButton.setGeometry(QtCore.QRect(390, 580, 241, 51))
        self.recoveryPasswordPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: green;")
        self.recoveryPasswordPushButton.setObjectName("recoveryPasswordPushButton")
        self.emailField = QtWidgets.QLineEdit(self.widget)
        self.emailField.setGeometry(QtCore.QRect(380, 140, 461, 71))
        self.emailField.setObjectName("emailField")
        self.cancelPushButton = QtWidgets.QPushButton(self.widget)
        self.cancelPushButton.setGeometry(QtCore.QRect(670, 580, 171, 51))
        self.cancelPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: red;")
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.oldPasswordField = QtWidgets.QLineEdit(self.widget)
        self.oldPasswordField.setGeometry(QtCore.QRect(380, 230, 461, 71))
        self.oldPasswordField.setObjectName("oldPasswordField")
        self.newPasswordField = QtWidgets.QLineEdit(self.widget)
        self.newPasswordField.setGeometry(QtCore.QRect(380, 320, 461, 71))
        self.newPasswordField.setObjectName("newPasswordField")
        self.renewPasswordField = QtWidgets.QLineEdit(self.widget)
        self.renewPasswordField.setGeometry(QtCore.QRect(380, 410, 461, 71))
        self.renewPasswordField.setObjectName("renewPasswordField")

        self.retranslateUi(RenewPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(RenewPasswordDialog)

    def retranslateUi(self, RenewPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        RenewPasswordDialog.setWindowTitle(_translate("RenewPasswordDialog", "Dialog"))
        self.recoveryPasswordLabel.setText(_translate("RenewPasswordDialog", "Смена пароля"))
        self.recoveryPasswordPushButton.setText(_translate("RenewPasswordDialog", "Сменить пароль"))
        self.emailField.setPlaceholderText(_translate("RenewPasswordDialog", "   Адрес электронной почты"))
        self.cancelPushButton.setText(_translate("RenewPasswordDialog", "Отмена"))
        self.oldPasswordField.setPlaceholderText(_translate("RenewPasswordDialog", "   Старый пароль"))
        self.newPasswordField.setPlaceholderText(_translate("RenewPasswordDialog", "   Новый пароль"))
        self.renewPasswordField.setPlaceholderText(_translate("RenewPasswordDialog", "   Подтвердите новый пароль"))
