# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUpDialog(object):
    def setupUi(self, SignUpDialog):
        SignUpDialog.setObjectName("SignUpDialog")
        SignUpDialog.resize(1175, 797)
        self.widget = QtWidgets.QWidget(SignUpDialog)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 1221, 801))
        self.widget.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.widget.setObjectName("widget")
        self.signupLabel = QtWidgets.QLabel(self.widget)
        self.signupLabel.setGeometry(QtCore.QRect(440, 50, 331, 131))
        self.signupLabel.setStyleSheet("font: 28pt \"DejaVu Math TeX Gyre\";\n"
"color: black;")
        self.signupLabel.setObjectName("signupLabel")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 460, 451, 71))
        self.errorLabel.setStyleSheet("color: red;\n"
"font: 18pt \"Cantarell\";\n"
"")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.signUpPushButton = QtWidgets.QPushButton(self.widget)
        self.signUpPushButton.setGeometry(QtCore.QRect(370, 570, 211, 51))
        self.signUpPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: green;")
        self.signUpPushButton.setObjectName("signUpPushButton")
        self.nameuserField = QtWidgets.QLineEdit(self.widget)
        self.nameuserField.setGeometry(QtCore.QRect(370, 200, 461, 71))
        self.nameuserField.setObjectName("nameuserField")
        self.passwordField = QtWidgets.QLineEdit(self.widget)
        self.passwordField.setGeometry(QtCore.QRect(370, 290, 461, 71))
        self.passwordField.setObjectName("passwordField")
        self.confirmField = QtWidgets.QLineEdit(self.widget)
        self.confirmField.setGeometry(QtCore.QRect(370, 380, 461, 71))
        self.confirmField.setObjectName("confirmField")
        self.cancelPushButton = QtWidgets.QPushButton(self.widget)
        self.cancelPushButton.setGeometry(QtCore.QRect(630, 570, 191, 51))
        self.cancelPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: red;")
        self.cancelPushButton.setObjectName("cancelPushButton")

        self.retranslateUi(SignUpDialog)
        QtCore.QMetaObject.connectSlotsByName(SignUpDialog)

    def retranslateUi(self, SignUpDialog):
        _translate = QtCore.QCoreApplication.translate
        SignUpDialog.setWindowTitle(_translate("SignUpDialog", "Dialog"))
        self.signupLabel.setText(_translate("SignUpDialog", "Регистрация"))
        self.signUpPushButton.setText(_translate("SignUpDialog", "Ok"))
        self.nameuserField.setPlaceholderText(_translate("SignUpDialog", "   e-mail"))
        self.passwordField.setPlaceholderText(_translate("SignUpDialog", "   Пароль"))
        self.confirmField.setPlaceholderText(_translate("SignUpDialog", "   Повторите пароль"))
        self.cancelPushButton.setText(_translate("SignUpDialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUpDialog = QtWidgets.QDialog()
    ui = Ui_SignUpDialog()
    ui.setupUi(SignUpDialog)
    SignUpDialog.show()
    sys.exit(app.exec_())
