# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1178, 798)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1181, 801))
        self.widget.setMinimumSize(QtCore.QSize(831, 731))
        self.widget.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.widget.setObjectName("widget")
        self.labelWelcom = QtWidgets.QLabel(self.widget)
        self.labelWelcom.setGeometry(QtCore.QRect(380, 60, 551, 131))
        self.labelWelcom.setStyleSheet("font: 28pt \"DejaVu Math TeX Gyre\";\n"
"color: black;")
        self.labelWelcom.setObjectName("labelWelcom")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 390, 461, 71))
        self.errorLabel.setStyleSheet("color: red;\n"
"font: 14pt \"Cantarell\";")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.loginPushButton = QtWidgets.QPushButton(self.widget)
        self.loginPushButton.setGeometry(QtCore.QRect(240, 480, 191, 51))
        self.loginPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: green;")
        self.loginPushButton.setObjectName("loginPushButton")
        self.signupPushButton = QtWidgets.QPushButton(self.widget)
        self.signupPushButton.setGeometry(QtCore.QRect(490, 480, 211, 51))
        self.signupPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: grey;")
        self.signupPushButton.setObjectName("signupPushButton")
        self.cancelPushButton = QtWidgets.QPushButton(self.widget)
        self.cancelPushButton.setGeometry(QtCore.QRect(760, 480, 211, 51))
        self.cancelPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: red;")
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.nameuserLineEdit = QtWidgets.QLineEdit(self.widget)
        self.nameuserLineEdit.setGeometry(QtCore.QRect(380, 210, 461, 71))
        self.nameuserLineEdit.setObjectName("nameuserLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(380, 310, 461, 71))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.saveMeCheckBox = QtWidgets.QCheckBox(self.widget)
        self.saveMeCheckBox.setGeometry(QtCore.QRect(470, 550, 291, 71))
        self.saveMeCheckBox.setStyleSheet("font: 18pt \"Cantarell\";")
        self.saveMeCheckBox.setObjectName("saveMeCheckBox")
        self.echoPasswordCheckBox = QtWidgets.QCheckBox(self.widget)
        self.echoPasswordCheckBox.setGeometry(QtCore.QRect(470, 600, 291, 71))
        self.echoPasswordCheckBox.setStyleSheet("font: 18pt \"Cantarell\";")
        self.echoPasswordCheckBox.setObjectName("echoPasswordCheckBox")
        self.forgotPasswordPushButton = QtWidgets.QPushButton(self.widget)
        self.forgotPasswordPushButton.setGeometry(QtCore.QRect(490, 690, 231, 36))
        self.forgotPasswordPushButton.setStyleSheet("color: blue;\n"
"font: 14pt \"Cantarell\";\n"
"background-color: rgb(235, 235, 235);\n"
"border:0px;")
        self.forgotPasswordPushButton.setObjectName("forgotPasswordPushButton")
        self.changePasswordPushButton = QtWidgets.QPushButton(self.widget)
        self.changePasswordPushButton.setGeometry(QtCore.QRect(490, 740, 231, 36))
        self.changePasswordPushButton.setStyleSheet("color: blue;\n"
"font: 14pt \"Cantarell\";\n"
"background-color: rgb(235, 235, 235);\n"
"border:0px;")
        self.changePasswordPushButton.setObjectName("changePasswordPushButton")
        self.helpPushButton = QtWidgets.QPushButton(self.widget)
        self.helpPushButton.setGeometry(QtCore.QRect(1060, 10, 113, 36))
        self.helpPushButton.setStyleSheet("background-color: rgb(8, 255, 16);")
        self.helpPushButton.setObjectName("helpPushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelWelcom.setText(_translate("Dialog", "Окно авторизации"))
        self.loginPushButton.setText(_translate("Dialog", "Войти"))
        self.signupPushButton.setText(_translate("Dialog", "Регистрация"))
        self.cancelPushButton.setText(_translate("Dialog", "Выход"))
        self.nameuserLineEdit.setPlaceholderText(_translate("Dialog", "   e-mail"))
        self.passwordLineEdit.setWhatsThis(_translate("Dialog", "<html><head/><body><p>sdefesrgvesrgvegrvevgre</p><p>vrbge</p></body></html>"))
        self.passwordLineEdit.setPlaceholderText(_translate("Dialog", "   Пароль"))
        self.saveMeCheckBox.setText(_translate("Dialog", "Запомнить меня"))
        self.echoPasswordCheckBox.setText(_translate("Dialog", "Показать пароль"))
        self.forgotPasswordPushButton.setText(_translate("Dialog", "Забыли пароль?"))
        self.changePasswordPushButton.setText(_translate("Dialog", "Сменить пароль"))
        self.helpPushButton.setText(_translate("Dialog", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
